Repository discord-modmail/modmail, pull requests merged in 2021-11, with the labels that each got.

#109 fix: only import bot when type checking modmail.utils.cogs
  modmail/utils/cogs.py
Labels: s: approved, a: tests, t: chore, skip changelog, a: bot, hacktoberfest-accepted

#110 hotfix: patch embeds throughout the entire test suite
  tests/conftest.py
  tests/modmail/conftest.py
  tests/modmail/utils/test_embeds.py
Labels: p: high, s: approved, a: tests, t: chore, skip changelog, hacktoberfest-accepted

#114 Revert #86: Remove dependabot
  .github/dependabot.yml
  .github/workflows/update_requirements_dependabot.yml
Labels: p: high, a: tools, t: chore, skip changelog

#111 scripts: add wrapper to run scripts by invoking the scripts module
  poetry.lock
  pyproject.toml
  scripts/__init__.py
  scripts/__main__.py
Labels: p: normal, s: needs review, a: tools, t: chore, skip changelog

#121 feat: add windows and mac testing
  .codecov.yml
  .github/workflows/lint_test.yml
  docs/changelog.md
Labels: a: CI, skip changelog

#119 ci: test on python3.10
  .github/workflows/lint_test.yml
  docs/changelog.md
  poetry.lock
  requirements.txt
Labels: a: CI, t: feature

#120 Tests: patch os.environ to exclude tests
  .gitignore
  tests/modmail/conftest.py
  tests/modmail/test.env
Labels: s: needs review, a: tests, t: chore, skip changelog

#122 deps: upgrade to 3.10 supported wheels
  poetry.lock
  requirements.txt
Labels: a: dependencies, p: high, s: needs review, skip changelog

#127 ci: switch to coveralls
  .codecov.yml
  .github/workflows/lint_test.yml
  README.md
  poetry.lock
  pyproject.toml
Labels: a: CI, p: normal, s: needs review, a: tools, skip changelog

#131 ci: run flake8 black on pre commit failure
  .github/workflows/lint_test.yml
Labels: a: CI, p: normal, skip changelog

#125 tests: mock aiohttp responses and fix windows
  modmail/__init__.py
  modmail/bot.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_fixtures.py
Labels: s: needs review, a: tests, skip changelog

#132 tools: remove flake8-bandit
  poetry.lock
  pyproject.toml
Labels: s: needs review, a: tools, skip changelog

#133 Add lock no update task
  pyproject.toml
Labels: a: dependencies, a: tools, skip changelog
