Repository discord-modmail/modmail, pull requests merged in 2021-07, with the labels that each got.

#21 Update CI, dev enviroment, pyproject.toml, add tests
  .github/CODEOWNERS
  .github/workflows/lint.yml
  .github/workflows/lint_test.yml
  .github/workflows/status_embed.yml
  .gitignore
  .pre-commit-config.yaml
  codecov.yml
  modmail/__main__.py
  poetry.lock
  pyproject.toml
  requirements.txt
  tests/__init__.py
  tests/test_test.py
  tox.ini
Labels: a: CI, a: dependencies, a: tests, a: tools, p: high, s: needs review, t: enhancement

#20 Create SECURITY.md
  SECURITY.md
Labels: a: documentation, help wanted, p: normal, s: needs review, t: enhancement

#26 add badges to readme
  README.md
Labels: a: documentation, l: beginner, p: low, s: ready for review, t: enhancement
