Repository discord-modmail/modmail, pull requests merged in 2021-06, with the labels that each got.

#11 Adds Discord OAuth2 login to site
  .env.example
  .flake8
  modmail/bot.py
  poetry.lock
  pyproject.toml
  requirements.txt
  website/constants.py
  website/main.py
Labels: area: site, enhancement

#16 add github workflow embed
  .github/workflows/lint.yml
  .github/workflows/status_embed.yml
Labels: a: CI, s: needs review

#17 add additional event variables
  .github/workflows/status_embed.yml
Labels: a: CI

#18 Mark tailwind.css as a vendored file
  .gitattributes
Labels: a: tools
