Repository discord-modmail/modmail, pull requests merged in 2021-08, with the labels that each got.

#35 Update CODEOWNERS to remove `site` and add myself
  .github/CODEOWNERS
Labels: a: tools, l: beginner, p: normal, s: approved, t: chore

#36 Create fossa action
  .github/workflows/fossa_status.yml
Labels: a: CI, a: dependencies, a: tools, l: intermediate, p: normal, s: approved, t: enhancement

#29 migrate to discord.py v2
  poetry.lock
  pyproject.toml
Labels: a: bot, a: dependencies, l: intermediate, p: normal, s: WIP, t: enhancement

#31 Add issue and pr templates
  .github/ISSUE_TEMPLATE/bug_report_bot.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: l: beginner, p: low, s: approved, s: ready for review, t: enhancement

#27 update export task to not infintely loop
  pyproject.toml
Labels: a: dependencies, a: tools, l: beginner, p: high, s: ready for review, t: bug

#38 fix: relock dependencies
  poetry.lock
  requirements.txt
Labels: a: dependencies, a: tools, p: high, s: ready for review, t: chore

#41 Clean up logging file
  modmail/__init__.py
Labels: a: bot, p: normal, s: ready for review, t: chore

#37 feat: Create test suite
  .codecov.yml
  .github/workflows/lint_test.yml
  modmail/bot.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/docs.md
  tests/test_bot.py
  tests/test_logs.py
  tests/test_test.py
  tox.ini
Labels: a: bot, a: tests, p: normal, s: approved, s: ready for review, t: enhancement

#45 chore: remove fossa
  .github/workflows/fossa_status.yml
  README.md
Labels: l: beginner, p: normal, s: approved, s: ready for review, t: chore

#46 chore: tone down codecov
  .codecov.yml
Labels: a: CI, p: normal, s: approved, s: ready for review

#44 update pre-commit config
  .pre-commit-config.yaml
Labels: l: beginner, p: normal, s: approved, s: ready for review, a: tools, t: chore

#43 feat: extension and plugin loading system
  .codecov.yml
  .env.example
  .env.template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/changelog.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  Procfile
  README.md
  SECURITY.md
  modmail/__init__.py
  modmail/__main__.py
  modmail/bot.py
  modmail/config-default.toml
  modmail/config.py
  modmail/extensions/__init__.py
  modmail/extensions/extension_manager.py
  modmail/extensions/meta.py
  modmail/extensions/plugin_manager.py
  modmail/plugin_helpers.py
  modmail/plugins/.gitignore
  modmail/plugins/__init__.py
  modmail/plugins/local/README.md
  modmail/utils/cogs.py
  modmail/utils/extensions.py
  modmail/utils/plugins.py
  poetry.lock
  pyproject.toml
  requirements.txt
  runtime.txt
Labels: a: bot, l: intermediate, p: high, s: approved, s: ready for review, t: feature

#13 Add Docker Setup
  .gitignore
  Dockerfile
  docker-compose.yaml
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: l: intermediate, p: high, s: ready for review, t: feature, a: tools, skip changelog

#19 Add docker build to GHCR workflow
  .github/workflows/build.yml
Labels: a: CI, p: normal, s: stalled, a: tools, skip changelog

#59 chore: make codecov support coverage for the entire modmail folder
  .codecov.yml
Labels: a: CI, p: normal, s: ready for review, a: tools, skip changelog

#56 Refactor startup
  docs/changelog.md
  modmail/__main__.py
  modmail/bot.py
  tests/docs.md
  tests/test_bot.py
Labels: a: bot, p: high, s: approved, s: ready for review, t: chore

#47 chore: add coverage.py html server task
  pyproject.toml
Labels: p: normal, s: ready for review, a: tools, skip changelog

#58 chore[hosting]: use docker for hosting
  .pre-commit-config.yaml
  Procfile
  app.json
  docs/changelog.md
  heroku.yml
  runtime.txt
Labels: p: normal, s: approved, s: ready for review, t: chore

#67 deps: update dependencies and discord.py
  .pre-commit-config.yaml
  Dockerfile
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: a: dependencies, s: ready for review, t: chore, skip changelog

#66 tools/touch up
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  tox.ini
Labels: a: CI, s: approved, s: ready for review, a: tools, t: chore, skip changelog

#61 chore: use raw docstrings to remove w605 ignore
  modmail/bot.py
  modmail/extensions/extension_manager.py
  modmail/extensions/plugin_manager.py
  modmail/log.py
Labels: a: bot, p: low, s: needs review, t: chore, skip changelog

#50 feat: interaction paginator
  docs/changelog.md
  modmail/extensions/extension_manager.py
  modmail/extensions/plugin_manager.py
  modmail/extensions/utils/__init__.py
  modmail/extensions/utils/paginator_manager.py
  modmail/utils/__init__.py
  modmail/utils/errors.py
  modmail/utils/pagination.py
  pyproject.toml
  tests/docs.md
  tests/modmail/utils/test_pagination.py
Labels: a: bot, l: intermediate, p: normal, s: needs review, t: feature
