Repository discord-modmail/modmail, pull requests merged in 2021-05, with the labels that each got.

#4 Fix: linting errors noticed by #3
  modmail/__main__.py
  modmail/bot.py
  modmail/log.py
Labels: P1: Urgent, bug

#5 Setup Procfile
  Procfile
  modmail/config.py
  pyproject.toml
  requirements.txt
Labels: P1: Urgent, enhancement

#9 Add shared startup functionality
  .flake8
  Procfile
  launcher.py
  modmail/bot.py
  pyproject.toml
  website/main.py
Labels: area: bot, area: site, enhancement

#10 Adds Codeowners
  .github/CODEOWNERS
Labels: documentation, good first issue, help wanted

#12 auto generate message at top of requirements.txt
  pyproject.toml
Labels: area: shared, bug
